<?php

/**
 * This is the model base class for the table "student_classroom".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudentClassroom".
 *
 * Columns in table "student_classroom" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $student_id
 * @property string $classroom_id
 *
 */
abstract class BaseStudentClassroom extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'student_classroom';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StudentClassroom|StudentClassrooms', $n);
	}

	public static function representingColumn() {
		return array(
			'student_id',
			'classroom_id',
		);
	}

	public function rules() {
		return array(
			array('student_id, classroom_id', 'required'),
			array('student_id, classroom_id', 'length', 'max'=>10),
			array('student_id, classroom_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'student_id' => null,
			'classroom_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('student_id', $this->student_id);
		$criteria->compare('classroom_id', $this->classroom_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}