<?php

/**
 * This is the model base class for the table "assignment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Assignment".
 *
 * Columns in table "assignment" available as properties of the model,
 * followed by relations of table "assignment" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $datecreated
 * @property string $datedue
 * @property string $notes
 *
 * @property Student[] $students
 * @property Grade[] $grades
 */
abstract class BaseAssignment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'assignment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Assignment|Assignments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>30),
			array('notes', 'length', 'max'=>200),
			array('datecreated, datedue', 'safe'),
			array('datecreated, datedue, notes', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, datecreated, datedue, notes', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'students' => array(self::MANY_MANY, 'Student', 'assignment_student(assignment_id, student_id)'),
			'grades' => array(self::MANY_MANY, 'Grade', 'grade_assignment(assignment_id, grade_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'students' => 'AssignmentStudent',
			'grades' => 'GradeAssignment',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'datecreated' => Yii::t('app', 'Datecreated'),
			'datedue' => Yii::t('app', 'Datedue'),
			'notes' => Yii::t('app', 'Notes'),
			'students' => null,
			'grades' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('datecreated', $this->datecreated, true);
		$criteria->compare('datedue', $this->datedue, true);
		$criteria->compare('notes', $this->notes, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}