<?php

/**
 * This is the model base class for the table "classroom".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Classroom".
 *
 * Columns in table "classroom" available as properties of the model,
 * followed by relations of table "classroom" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $root
 * @property string $lft
 * @property string $rgt
 * @property integer $level
 * @property integer $teacher_id
 *
 * @property Users $teacher
 * @property Student[] $students
 */
abstract class BaseClassroom extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classroom';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Classroom|Classrooms', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name,teacher_id', 'required'),
			array('teacher_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			
		
			array('id, name,teacher_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'students' => array(self::MANY_MANY, 'Student', 'student_classroom(classroom_id, student_id)'),
                        'teacher' => array(self::BELONGS_TO, 'User', 'teacher_id'),
		);
                
		
		if (isset(Yii::app()->getModule('user')->profileRelations)) $relations = array_merge($relations,Yii::app()->getModule('user')->profileRelations);
		return $relations;
	
	}

	public function pivotModels() {
		return array(
			'students' => 'StudentClassroom',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'root' => Yii::t('app', 'Root'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
			'teacher_id' => null,
			'teacher' => null,
			'students' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('root', $this->root, true);
		$criteria->compare('lft', $this->lft, true);
		$criteria->compare('rgt', $this->rgt, true);
		$criteria->compare('level', $this->level);
		$criteria->compare('teacher_id', $this->teacher_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}